# Generated by Django 5.0.7 on 2024-08-01 08:21

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Learnings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('DSA', 'DSA'), ('Web development', 'Web development'), ('App development', 'App development'), ('DBMS', 'DBMS'), ('android development', 'android development'), ('Data Science', 'Data Science'), ('OS', 'OS'), ('Networking', 'Networking'), ('Apptitude', 'Apptitude')], max_length=50)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('hours_learned', models.FloatField(validators=[django.core.validators.MinValueValidator(0.5)])),
                ('learning_detail', models.TextField(default='NA')),
                ('links', models.TextField(default='')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
