# Generated by Django 5.0.7 on 2024-08-01 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_learnings_learning_detail_learnings_links_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learnings',
            name='learning_detail',
        ),
        migrations.RemoveField(
            model_name='learnings',
            name='links',
        ),
        migrations.RemoveField(
            model_name='learnings',
            name='subject',
        ),
        migrations.AlterField(
            model_name='learnings',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='learnings',
            name='hours_learned',
            field=models.PositiveIntegerField(),
        ),
    ]
