# Generated by Django 5.0.7 on 2024-08-01 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_mylearninglist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyLearningList',
        ),
    ]
